#!/usr/bin/env perl

use v5.14;

use strict;
use warnings;

my $cmd = $ARGV[1];
my @actions = `php artisan list --format=json | jq -r '.namespaces.[].commands[]'`;

if ($ENV{COMP_LINE}) {
    @actions = grep /^$cmd/, @actions;

    say "AQUI $cmd";
    map { /^$cmd/ && say $_} @actions;
    exit 0;
}

exec("php artisan @ARGV");
