#!/usr/bin/env ruby

actions = `php artisan list --format=json | jq -r '.namespaces.[].commands[]'`

if ENV['COMP_LINE']
  p ARGV
  actions.each_line { |action| puts action if action =~ /^#{ARGV[0]}/ }
  exit 0
end

exec("php artisan #{ARGV.join(' ')}")
