#!/usr/bin/env perl

use strict;
use warnings;

my $gitconfig_path = "$ENV{HOME}/.gitconfig";
my $theme = shift @ARGV; # Get the theme from command line arguments

# Check if a valid theme is provided
unless ($theme && ($theme eq 'dark' || $theme eq 'light')) {
    die "Usage: $0 [dark|light]\n";
}

# Check if .gitconfig file exists
if (-e $gitconfig_path) {
    # Read the content of the .gitconfig file
    open my $input, '<', $gitconfig_path or die "Cannot open $gitconfig_path: $!";
    my @lines = <$input>;
    close $input;

    # Modify the lines containing "light = false" or "light = true" based on the provided theme
    foreach my $line (@lines) {
        if ($theme eq 'dark') {
            $line =~ s/light = true/light = false/;
        } elsif ($theme eq 'light') {
            $line =~ s/light = false/light = true/;
        }
    }

    # Write the modified content back to the .gitconfig file
    open my $output, '>', $gitconfig_path or die "Cannot open $gitconfig_path for writing: $!";
    print $output @lines;
    close $output;

    print "Updated .gitconfig: light = ", ($theme eq 'light' ? 'true' : 'false'), "\n";
} else {
    print "Error: .gitconfig file not found.\n";
}
